### ISSUE TITLE
Format with Fourmolu

### ISSUE THREAD

**Issue by ocharles** [ocharles/weeder#123]
@ryndubei Now that we've got multiple people working on this, I think it might be worth using a formatter, rather than having people faff around with the (somewhat esoteric) formatting I used when I started this project. At CircuitHub, we use the following `fourmolu.yaml`:

```yaml
indentation: 2
comma-style: leading
import-export-style: diff-friendly
indent-wheres: true
record-brace-space: false
respectful: true
haddock-style: multi-line
newlines-between-decls: 2
fixities: []
single-constraint-parens: auto
```

What do you think? Shall we apply this here too? I also suggest we drop the package comments for now, though https://github.com/circuithub/ch-hs-imports does exist to automate this if we want it.
